trigger:
  - main

pr: none

variables:
  azureContainerRegistry.repository: "benefits-newsfeed"
  azureContainerRegistry.name: "acrbenefitsnewsfeed"
  azureContainerRegistry.domain: "acrbenefitsnewsfeed.azurecr.io"
  vmImageName: "ubuntu-latest"

stages:
  - stage: Build
    displayName: Build and Push to ACR
    jobs:
      - job: Build
        displayName: Build and Push Container
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: "$(azureContainerRegistry.name)"
              repository: "$(azureContainerRegistry.repository)"
              command: "login"
          - script: "docker pull $(azureContainerRegistry.domain)/$(azureContainerRegistry.repository):latest"
            displayName: Pull latest for layer caching
            continueOnError: true
          - task: Docker@2
            inputs:
              containerRegistry: '$(azureContainerRegistry.name)'
              repository: '$(azureContainerRegistry.repository)'
              command: 'build'
              Dockerfile: './astro-frontend/Dockerfile'
              tags: |
                $(tag)
                latest
                release-candidate
              arguments: '--pull'

          - task: Docker@2
            inputs:
              containerRegistry: "$(azureContainerRegistry.name)"
              repository: "$(azureContainerRegistry.repository)"
              command: "push"
              tags: |
                $(tag)
                latest
                release-candidate
