name: Dynamic Application Security Tests

on:
  push:
    branches: [main]

defaults:
  run:
    working-directory: ./astro-frontend

jobs:
  zap-proxy-scan:
    name: ZAP Proxy Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Build
        run: docker build -t astro-frontend .
        env:
          CI: true

      - name: Docker run
        run: docker run -d -p 4321:4321 astro-frontend
        env:
          CI: true

      - name: OWASP ZAP FULL Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: "http://localhost:4321"
          fail_action: "false"
          token: ${{ secrets.GITHUB_TOKEN }}
